### ISSUE TITLE
Why does `carthage update` always perform a checkout?

### ISSUE THREAD

**Issue by zhangxqq** [iabudiab/ObjectiveRocks#1]
I check out by carthage, always show:"Checking out ObjectiveRocks at "0.7.0" for long time, not success

**Comment by iabudiab** [comment]
@zhangxqq Hey there, this is not an issue with `ObjectiveRocks` but rather the way `carthage` works. It always checks out the dependencies before compiling. If you do not want this behaviour then you should run carthage with the `--no-checkout` flag like this:

`carthage update --no-checkout`

I hope I've understood your question correctly. Otherwise let me know if you did mean something else. Will be glad to help ;)

**Comment by iabudiab** [comment]
@zhangxqq Hey there, does the above answer your question? If so, I would close the issue now. Feel free to reopen if it's not the case.
