### ISSUE TITLE
General question: thread safety

### ISSUE THREAD

**Issue by iwasrobbed-ks** [iabudiab/ObjectiveRocks#15]
Hi @iabudiab 👋 This is more a general question: Do you happen to know which parts of this framework are / aren't thread safe, if any?

There are a few `@synchronized` calls, but wondering if you had any high level advice around concurrency. I'm looking into a concurrent reader/writer design (concurrent reads, serial writes with a barrier to block reads) so just trying to understand how ObjectiveRocks and RocksDB will play into that.

Thank you for any input! 🙏

**Comment by iabudiab** [comment]
Hey @rob-keepsafe 👋 

Good question 🤔

Implementing `ObjectiveRocks` I tried to encapsulate each native `rocksdb` struct/pointer in one Objective-C wrapper. Also I tried to prevent having any shared state apart from the native handle. The reasoning behind this was to delegate all threading details to the underlying rocksdb implementation without introducing own race conditions.

The rocksdb documentation mentions concurrency in a very small paragraph here: [https://github.com/facebook/rocksdb/wiki/Basic-Operations#concurrency](https://github.com/facebook/rocksdb/wiki/Basic-Operations#concurrency)

The relevant parts are:

- "Within a single process, the same rocksdb::DB object may be safely shared by multiple concurrent threads. I.e., different threads may write into or fetch iterators or call Get on the same database without any external synchronization (the rocksdb implementation will automatically do the required synchronization)."

This leads me to beleive, that operations in `RocksDB.mm` are thread safe, because it just delegates all the work to the native `rocksdb::DB` handle.

- "However other objects (like Iterator and WriteBatch) may require external synchronization. If two threads share such an object, they must protect access to it using their own locking protocol."

The `RocksDBIterator.mm` and `RocksDBWriteBatch.mm` wrappers are not *completely* thread safe according to this statement. 

If you take a look at the public headers of `rocksdb` then calling `const` methods is also safe without any external sync.

See here:  [https://github.com/facebook/rocksdb/blob/9a31b8dd2c293d92fb15524a97b63ded003f53c0/include/rocksdb/iterator.h#L14](https://github.com/facebook/rocksdb/blob/9a31b8dd2c293d92fb15524a97b63ded003f53c0/include/rocksdb/iterator.h#L14)

and here: 
[https://github.com/facebook/rocksdb/blob/9a31b8dd2c293d92fb15524a97b63ded003f53c0/include/rocksdb/write_batch.h#L20](https://github.com/facebook/rocksdb/blob/9a31b8dd2c293d92fb15524a97b63ded003f53c0/include/rocksdb/write_batch.h#L20)

`const` methods are those that do not mutate state, for example the iterator's `- (NSData *)key` and `- (NSData *)value` methods, which call the underlying `virtual Slice key() const = 0;` and `virtual Slice value() const = 0;`


Having said that, I haven't really tested ObjectiveRocks specifically for thread safety. The `@synchronized` calls are currently only used when `nulling` the native handle for a clean dealloc lifecycle. I remember having a couple of `EXC_BAD_ACCESS`s when switching view controllers in one app.

As to the concurrent reader/writer design, I recommend you to take a look at the public `rocksdb` headers of the native handle in use by ObjectiveRocks. Those are usually pretty clear about threading semantics. As a rule of thumb, methods mutating state usually need extra attention.

Synchronizing the access, however, shouldn't be a problem. The easiest approach would be to wrap those races into a serial queue, maybe something like this:

```swift
let serialQueue = DispatchQueue(label: "rocksqueue")

func read(): Data {
    var res: Data
    serialQueue.sync { 
        res = rocks.data(forKey: "key")
    }
    return res
}

func write(data: Data) {
    serialQueue.sync { // or .async(flags: .barrier) {..}
        rocks.setData(data, forKey: "key")
    }
}
```

I hope this helps.

Give me a shout if you would like to discuss/brain storm some specific ideas 😉

**Comment by iwasrobbed-ks** [comment]
Thanks for the thorough answer, @iabudiab ! This should give us a great place to start digging in further
