### ISSUE TITLE
About GPL LICENSE

### ISSUE THREAD

**Issue by whisper-bye** [iabudiab/ObjectiveRocks#5]
The facebook/rocksdb is released under the GPL-2.0 license.
if I use ObjectiveRocks with my iOS app project,
What are the risks of it?
ps. https://forums.developer.apple.com/thread/18922

thx.

**Comment by iabudiab** [comment]
@whisper-bye `rocksdb` is dual licensed under `GPL2` and `Apache2`.

Originally it had a `BSD-style` license with an extra Facebook patent clause. However, about two month ago, it was changed to `Apache2` See this commit: https://github.com/facebook/rocksdb/commit/3c327ac2d0fd50bbd82fe1f1af5de909dad769e6
and the corresponding PR: https://github.com/facebook/rocksdb/pull/2589

`GPL2` was added as an alternative in this commit: https://github.com/facebook/rocksdb/commit/d616ebea23fa88cb9c2c8588533526a566d9cfab for this PR: https://github.com/facebook/rocksdb/pull/2226

**What does all of this mean?**

I can only assume! I am not a lawyer nor do I have extensive knowledge in license laws. So don't take my words for it, investigate it further or ask an expert. All of the following is just my understanding of the situation and should not be interpreted as a legal advice.

My interpretation is that you, as a licensee, can choose under which license you want to use `rocksdb` code. Because:

* Apache2 is not compatible with GPL2 (see https://www.gnu.org/licenses/quick-guide-gplv3.html#new-compatible-licenses and https://www.apache.org/licenses/GPL-compatibility.html)
* rocksdb does not state, as far as I could tell, that both licenses apply at the same time (which would be weird due to the incompatibility)

**`ObjectiveRocks` and `rocksdb`**

ObjectiveRocks is MIT licensed which is compatible with Apache 2, so there should be no problems using them together under the Apache 2 license.

**Comment by whisper-bye** [comment]
@iabudiab thanks for your quick reply, I will consider your advice.
