### ISSUE TITLE
Publish to CocoaPods?

### ISSUE THREAD

**Issue by siuying** [iabudiab/ObjectiveRocks#6]
It seems the repo already have the latest podspec, any reason it is not on cocoapods yet?

**Comment by iabudiab** [comment]
@siuying Hey there. Good question, and yes, there is a reason.

The project does not pass the CocoaPods lint in order to publish it. When linting, CocoaPods copies the project, but not the source code (if I'm not mistaken), into some temp directory and builds it there. This messes up all of the C/C++ header imports of the `rocksdb` code.

If you find a way to structure the project in another way or do some other trick in order to pass CocoaPods validation, I'd really appreciate it.

**Comment by siuying** [comment]
I also cannot pass the lint. Somehow the Pods project did not set ROCKSDB_LITE=1 to the target, have yet to find way to make it work on lint.

**Comment by siuying** [comment]
If nothing works, we can still use `--skip-import-validation` option in pod trunk push, which will skip validation. https://github.com/CocoaPods/CocoaPods/issues/5152

**Comment by iabudiab** [comment]
@siuying I didn't know about the `--skip-import-validation` flag. Thanks for pointing it out 👍 
I'll give it a try now.

**Comment by iwasrobbed-ks** [comment]
Just wanted to sanity check: Are all the sources updated in the `.podspec` since it's last change was a year ago? I can help get this across the finish line over the next few weeks if needed

Definitely appreciate all your work on supporting this 👍

**Comment by iabudiab** [comment]
@rob-keepsafe Hey there.

The `.podspec` should be complete and ready to go. However the project wont build/lint via CocoaPods. That's why it's not published yet.

I have given it a try or two but didn't really invest much time in it.

The problem seems to be, that CocoaPods builds the project out-of-src, i.e. it copies the meta into some tmp folder and links to the source from there, which breaks all of the C++ imports.

I would greatly appreciate it, if you could figure it out 😄  But before you try, let me take a look at the spec and make sure that nothing is missing and/or something extra is being pulled in. Will comment here later to let you know 👍

**Comment by iabudiab** [comment]
@rob-keepsafe I've just pushed the updated `podspec` in 5c213e15d93749db39b8f11537221aa122b80c15

I'll try building and linting this with CocoaPods now.

**Comment by iwasrobbed-ks** [comment]
Awesome, thanks @iabudiab ! I ran a quick local build on latest develop using `pod spec lint --skip-import-validation --no-clean --verbose` (the `--no-clean` allows you to inspect, fix and re-build the CocoaPods built project after to figure out what's going on)

(Side note: use pod **lib** instead of pod **spec** e.g. `pod lib lint --skip-import-validation --no-clean` for local changes before pushing to origin)

Looks like fewer errors now, but still a few to clean up

E.g. in `RocksDBBackupEngine` changing:

```objc
rocksdb::BackupableDBOptions::BackupableDBOptions(_path.UTF8String)
```

to

```objc
rocksdb::BackupableDBOptions(_path.UTF8String)
```

And another in `xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb/table/block.h:23:10: fatal error: 'db/dbformat.h' file not found`

**Comment by iabudiab** [comment]
@rob-keepsafe Sounds good! Thanks a lot for pitching in 👍 

Just to let you know:
I've just pushed three _minor_ changes to the umbrella header, and the iOS excludes in `podspec`. And in case you haven't noticed, I've updated `rocksdb` to latest release 5.11.3 in 884b3b9bbbd2844a86d530e9be682e9256d16aa1

_Edit: Wont be able to comment/reply till later today, have some other stuff to take care of._

**Comment by iwasrobbed-ks** [comment]
@iabudiab Sounds good! I'll be working on this in my free time a little each day, but have some other work this week. 

We'll get through it slowly but surely and then once we get it working we can put a validation at the end of `.travis.yml` like `pod lib lint --allow-warnings` to ensure it's caught when it breaks

**Comment by iwasrobbed-ks** [comment]
@iabudiab I made a little progress this afternoon getting it to build for iOS (just a smoke test build, not an actual integration test). I'll work on macOS tomorrow, and then see if I can get some sort of integration test example working for each platform.

Since there are so many extraneous files in the `rocksdb` directory (that we're using as a submodule), I'm essentially copying them into a cleaned `rocksdb_src/rocksdb` folder and then stripping away all files except actual source.

With this approach, this means we'll generate a `rocksdb_src` (done only one time, after the pod is downloaded), but we'll also know that the only files within that folder are actual source and not tests, docs, java, etc. This makes it very easy to integrate rocksdb version changes into the macOS/iOS frameworks or `.podspec` files. You don't need to worry about storing that cleaned source in this repo.

Here are the commits so far: https://github.com/rob-keepsafe/ObjectiveRocks/commits/fix/podspec

There are quite a lot of warnings, but luckily you can silence those a bit (I'll see if I can do that in another commit later on).

You have two documentation warnings in your own code though:

>- WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/Code/RocksDBWriteBatch.h:70:9: warning: parameter 'data' not found in the function declaration [-Wdocumentation]
>- WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/Code/RocksDB.h:276:13: warning: empty paragraph passed to '@discussion' command [-Wdocumentation]

Here is the end of the build output:

```shell
** BUILD SUCCEEDED **

   Testing with xcodebuild.
 -> ObjectiveRocks (0.8.0)
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/table/block_based_table_reader.cc:251:61: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/table/block_based_table_reader.cc:645:20: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/table/block_based_table_reader.cc:647:30: warning: implicit conversion loses integer precision: 'unsigned long long' to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/table/block_based_table_reader.cc:1640:42: warning: implicit conversion loses integer precision: 'unsigned long long' to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/utilities/col_buf_decoder.cc:150:27: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >::size_type' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/utilities/col_buf_decoder.cc:225:29: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >::size_type' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/compaction_job.cc:726:52: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'const size_t' (aka 'const unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/compaction_job.cc:733:37: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >::value_type' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/compaction_picker.cc:44:45: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/db_impl_write.cc:224:13: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/db_impl_write.cc:551:11: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/db_impl_write.cc:1348:41: warning: implicit conversion loses integer precision: 'unsigned long long' to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/db_impl_write.cc:1352:57: warning: implicit conversion loses integer precision: 'const uint64_t' (aka 'const unsigned long long') to 'const unsigned long' [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/db_iter.cc:1090:9: warning: variable 'cmp' may be uninitialized when used here [-Wconditional-uninitialized]
    - NOTE  | xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/db_iter.cc:1081:10: note: initialize the variable 'cmp' to silence this warning
    - WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/env/env_posix.cc:277:7: warning: code will never be executed [-Wunreachable-code]
    - WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/env/env_posix.cc:365:7: warning: code will never be executed [-Wunreachable-code]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/util/file_reader_writer.cc:519:37: warning: implicit conversion loses integer precision: 'unsigned long long' to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/util/file_reader_writer.cc:552:65: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/util/file_reader_writer.cc:557:42: warning: implicit conversion loses integer precision: 'unsigned long long' to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/util/file_reader_writer.cc:617:37: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/util/file_reader_writer.cc:620:29: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/util/file_reader_writer.cc:624:36: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/monitoring/histogram_windowing.cc:63:17: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/monitoring/histogram_windowing.cc:93:19: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/monitoring/histogram_windowing.cc:93:59: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/monitoring/histogram_windowing.cc:133:21: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/monitoring/histogram_windowing.cc:152:50: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/log_writer.cc:61:63: warning: implicit conversion loses integer precision: 'const int64_t' (aka 'const long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/table/partitioned_filter_block.cc:282:59: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/Code/RocksDBWriteBatch.h:70:9: warning: parameter 'data' not found in the function declaration [-Wdocumentation]
    - WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/Code/RocksDB.h:276:13: warning: empty paragraph passed to '@discussion' command [-Wdocumentation]
    - WARN  | xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/write_thread.cc:175:8: warning: variable 'state' may be uninitialized when used here [-Wconditional-uninitialized]
    - NOTE  | xcodebuild:  /Users/rob/ObjectiveRocks/rocksdb_cleaned/rocksdb/db/write_thread.cc:58:16: note: initialize the variable 'state' to silence this warning

Pods workspace available at `/var/folders/sm/p6n9r_9n71x6y6j1f8f6d70r0000gp/T/CocoaPods-Lint-20180523-34137-b8j0sg-ObjectiveRocks/App.xcworkspace` for inspection.

ObjectiveRocks passed validation.
```

**Comment by iwasrobbed-ks** [comment]
Alternatively, I can see if I can get this working with just the `rocksdb` submodule and using excludes but I was having a number of issues with the builds and which files to include since they mix in tests, benchmarks, etc.

It'd also be really nice to have a way to easily diff new rocksdb releases for changes (which we could easily do with the clean source script).

Let me know which direction you'd like to go 👍

**Comment by iwasrobbed-ks** [comment]
Opened up a PR supporting iOS and macOS here with two integration tests as well: https://github.com/iabudiab/ObjectiveRocks/pull/9
